#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 VPlayer contributors
# SPDX-License-Identifier: GPL-3.0-only
# SPDX-FileComment: Apple App Store distribution is additionally permitted by LICENSE.APPSTORE-EXCEPTION.
"""Exercise generated-input transfer with the production and coverage schemes."""
from pathlib import Path
import base64
import json
import os
import shutil
import subprocess
import sys
import tempfile
import unittest

ROOT = Path(__file__).resolve().parents[2]
SCHEMES = ('VPlayer', 'VPlayerCoverage', 'VPlayerRelease',
           'VPlayerReleaseBoundaryTests', 'VPlayerReleaseStartupTests',
           'VPlayerHLSAcceptance', 'VPlayeriOS', 'VPlayeriOSCoverage',
           'VPlayeriOSRelease', 'VPlayeriOSReleaseStartup', 'VPlayeriOSBenchmarks')
NEW_SCHEMES = ('VPlayerCoverage', 'VPlayerRelease', 'VPlayeriOSCoverage', 'VPlayeriOSRelease')


def scheme_path(name):
    return 'VPlayer.xcodeproj/xcshareddata/xcschemes/' + name + '.xcscheme'


class GeneratedInputTransferTests(unittest.TestCase):
    def setUp(self):
        temporary = tempfile.TemporaryDirectory()
        self.addCleanup(temporary.cleanup)
        self.root = Path(temporary.name)
        (self.root / 'Scripts').mkdir()
        self.script = self.root / 'Scripts/emit-generated-ios-inputs.py'
        shutil.copyfile(ROOT / 'Scripts/emit-generated-ios-inputs.py', self.script)
        self.paths = (['VPlayer.xcodeproj/project.pbxproj'] +
                      [scheme_path(name) for name in SCHEMES] +
                      ['Sources/VPlayerPlayback/Resources/' + name + '.metallib'
                       for name in ('VPlayerPlayback-ios', 'VPlayerPlayback-iphonesimulator')])
        for name in self.paths:
            path = self.root / name
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(b'original generated bytes\n')
        self.baseline = self.root / 'baseline.json'
        self.output = self.root / 'output.txt'

    def run_tool(self, mode):
        return subprocess.run([sys.executable, str(self.script), mode,
                               '--baseline', str(self.baseline)], capture_output=True,
                              text=True, env={**os.environ, 'GITHUB_OUTPUT': str(self.output)},
                              timeout=5)

    def test_capture_includes_every_scheme_that_must_be_regenerated(self):
        result = self.run_tool('capture')
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertCountEqual(json.loads(self.baseline.read_text()), self.paths)

    def test_new_production_and_coverage_schemes_round_trip_exact_bytes(self):
        for name in NEW_SCHEMES:
            with self.subTest(scheme=name):
                captured = self.run_tool('capture')
                self.assertEqual(captured.returncode, 0, captured.stderr)
                path = scheme_path(name)
                changed = ('new ' + name + ' bytes\n').encode()
                (self.root / path).write_bytes(changed)
                emitted = self.run_tool('emit')
                self.assertEqual(emitted.returncode, 0, emitted.stderr)
                self.assertIn('GENERATED_INPUTS_NEED_REFRESH=true', emitted.stdout)
                payloads = {}
                current = None
                for line in emitted.stdout.splitlines():
                    if line.startswith('VPLAYER_GENERATED_BEGIN '):
                        current = json.loads(line.split(' ', 1)[1])['path']
                        payloads[current] = bytearray()
                    elif line.startswith('VPLAYER_GENERATED_DATA '):
                        payloads[current] += base64.b64decode(line.split(' ', 1)[1])
                self.assertEqual(payloads[path], changed)

    def test_missing_new_scheme_fails_closed_instead_of_claiming_no_refresh(self):
        captured = self.run_tool('capture')
        self.assertEqual(captured.returncode, 0, captured.stderr)
        (self.root / scheme_path('VPlayeriOSRelease')).unlink()
        emitted = self.run_tool('emit')
        self.assertNotEqual(emitted.returncode, 0)
        self.assertIn('Generator omitted a required input', emitted.stderr)
        self.assertNotIn('NEED_REFRESH=false', emitted.stdout)


if __name__ == '__main__':
    unittest.main()
